/**
 * Config Package Guides
 *
 * Comprehensive documentation for @idealyst/config.
 */

export const configGuides: Record<string, string> = {
  "idealyst://config/overview": `# @idealyst/config

Cross-platform environment variable management. Reads from \`.env\` files (native) and \`import.meta.env\` (web/Vite) with a unified API.

## Installation

\`\`\`bash
yarn add @idealyst/config
\`\`\`

## Platform Support

| Platform | Status |
|----------|--------|
| Web      | ✅ Vite import.meta.env (strips VITE_ prefix) |
| iOS      | ✅ react-native-config |
| Android  | ✅ react-native-config |
| Node     | ✅ dotenv |

## Key Exports

\`\`\`typescript
import { config } from '@idealyst/config';
import type { IConfig, ConfigValidationError, ConfigKeys } from '@idealyst/config';
\`\`\`

## Quick Start

\`\`\`tsx
import { config } from '@idealyst/config';

// Get a value (returns undefined if not set)
const apiUrl = config.get('API_URL');

// Get a required value (throws if not set)
const secretKey = config.getRequired('SECRET_KEY');

// Check existence
if (config.has('FEATURE_FLAG')) {
  // ...
}

// Validate required keys on app startup
config.validate(['API_URL', 'AUTH_URL', 'APP_NAME']);
\`\`\`
`,

  "idealyst://config/api": `# @idealyst/config — API Reference

## config (singleton)

The default \`config\` instance reads from the platform-appropriate source.

### IConfig Interface

\`\`\`typescript
interface IConfig {
  /**
   * Get a configuration value by key.
   * Keys are canonical (without VITE_ prefix on web).
   * @returns The value, or defaultValue, or undefined
   */
  get(key: string, defaultValue?: string): string | undefined;

  /**
   * Get a required configuration value.
   * @throws Error if key is not defined
   */
  getRequired(key: string): string;

  /**
   * Check if a configuration key exists.
   */
  has(key: string): boolean;

  /**
   * Get all available configuration keys.
   */
  keys(): string[];

  /**
   * Validate that all required keys are present.
   * @throws ConfigValidationError if any keys are missing
   */
  validate(requiredKeys: string[]): void;
}
\`\`\`

### ConfigValidationError

\`\`\`typescript
class ConfigValidationError extends Error {
  readonly missingKeys: string[];
}
\`\`\`

Thrown by \`config.validate()\` when required keys are missing.

---

## Key Naming

| Platform | Env var | config.get() key |
|----------|---------|------------------|
| Web (Vite) | \`VITE_API_URL\` | \`'API_URL'\` |
| Native | \`API_URL\` | \`'API_URL'\` |
| Node | \`API_URL\` | \`'API_URL'\` |

The \`VITE_\` prefix is automatically stripped on web.

---

## Type Augmentation

Run \`idealyst-config generate\` to augment the \`ConfigKeys\` interface with your actual env vars for autocomplete:

\`\`\`typescript
// Generated by idealyst-config generate:
declare module '@idealyst/config' {
  interface ConfigKeys {
    API_URL: string;
    AUTH_URL: string;
    APP_NAME: string;
  }
}
\`\`\`
`,

  "idealyst://config/examples": `# @idealyst/config — Examples

## App Initialization

\`\`\`tsx
import { config } from '@idealyst/config';

// Validate required config at app startup
function initializeApp() {
  try {
    config.validate(['API_URL', 'AUTH_URL', 'APP_NAME']);
  } catch (error) {
    if (error instanceof ConfigValidationError) {
      console.error('Missing config keys:', error.missingKeys);
      throw error;
    }
  }

  return {
    apiUrl: config.getRequired('API_URL'),
    authUrl: config.getRequired('AUTH_URL'),
    appName: config.getRequired('APP_NAME'),
    debugMode: config.get('DEBUG') === 'true',
  };
}
\`\`\`

## API Client Setup

\`\`\`tsx
import { config } from '@idealyst/config';

const apiClient = {
  baseUrl: config.getRequired('API_URL'),
  timeout: parseInt(config.get('API_TIMEOUT', '30000') ?? '30000', 10),

  async fetch(path: string, options?: RequestInit) {
    const response = await fetch(\`\${this.baseUrl}\${path}\`, {
      ...options,
      headers: {
        'Content-Type': 'application/json',
        ...options?.headers,
      },
    });
    return response.json();
  },
};
\`\`\`

## Feature Flags

\`\`\`tsx
import { config } from '@idealyst/config';

const features = {
  newDashboard: config.get('FEATURE_NEW_DASHBOARD') === 'true',
  darkMode: config.get('FEATURE_DARK_MODE', 'true') === 'true',
  analytics: config.has('ANALYTICS_KEY'),
};

function AppRouter() {
  return features.newDashboard ? <NewDashboard /> : <LegacyDashboard />;
}
\`\`\`

## OAuth Configuration

\`\`\`tsx
import { config } from '@idealyst/config';
import { createOAuthClient } from '@idealyst/oauth-client';

const googleAuth = createOAuthClient({
  oauthUrl: config.getRequired('API_URL') + '/auth/google',
  redirectUrl: config.getRequired('OAUTH_REDIRECT_URL'),
});
\`\`\`
`,
};
