version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: ${PROJECT_NAME:-idealyst}-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-idealyst_db}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - idealyst-network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: ${PROJECT_NAME:-idealyst}-redis
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - idealyst-network

  # API Service
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: api-runner
    container_name: ${PROJECT_NAME:-idealyst}-api
    environment:
      NODE_ENV: ${NODE_ENV:-production}
      PORT: 3000
      DATABASE_URL: postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@postgres:5432/${POSTGRES_DB:-idealyst_db}
      REDIS_URL: redis://redis:6379
    ports:
      - "${API_PORT:-3000}:3000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - idealyst-network

  # Web Application
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: web-runner
    container_name: ${PROJECT_NAME:-idealyst}-web
    ports:
      - "${WEB_PORT:-80}:80"
    depends_on:
      - api
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - idealyst-network

  # Development Service (for local development)
  dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    container_name: ${PROJECT_NAME:-idealyst}-dev
    environment:
      NODE_ENV: development
    ports:
      - "3000:3000"   # API dev server
      - "5173:5173"   # Vite dev server
      - "8080:8080"   # Additional dev server
      - "19006:19006" # Expo dev tools
    volumes:
      - .:/app
      - /app/node_modules
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - idealyst-network
    tty: true
    stdin_open: true

  # Test Runner
  test:
    build:
      context: .
      dockerfile: Dockerfile
      target: test-runner
    container_name: ${PROJECT_NAME:-idealyst}-test
    environment:
      NODE_ENV: test
      CI: true
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - idealyst-network
    profiles:
      - testing

volumes:
  postgres_data:
  redis_data:

networks:
  idealyst-network:
    driver: bridge
